//
//  Data.swift
//  Trivial
//
//  Created by Warren Hansen on 2/18/24.
//

import SwiftUI

enum Category: String, Codable, CaseIterable  {
    case presidents = "President"
    case usHistory = "US History"
    case worldHistory = "World History"
    case movies = "Movie"
    case television = "Television"
}

struct Trivia {
    let question: String
    let answer: String
    let category: Category
}

class DataViewModel {
    
    func selectQuestion(category: Category) -> [Trivia]  {
        switch category {
        case .presidents:
            return presidentQuestions
        case .usHistory:
            return usHistoryQuestions
        case .worldHistory:
            return presidentQuestions
        case .movies:
            return movieQuestions
        case .television:
            return tvShowQuestions
        }
    }
    
    let tvShowQuestions: [Trivia] = [
        Trivia(question: "In 'Friends', what is the name of Ross's second wife?", answer: "Emily", category: .television),
        Trivia(question: "Who played the character of Walter White in the TV show 'Breaking Bad'?", answer: "Bryan Cranston", category: .television),
        Trivia(question: "Which TV show features characters named Chandler, Joey, and Monica?", answer: "Friends", category: .television),
        Trivia(question: "Who is the primary antagonist in the TV series 'Game of Thrones'?", answer: "Night King", category: .television),
        Trivia(question: "In 'Stranger Things', what is the name of the parallel dimension?", answer: "The Upside Down", category: .television),
        Trivia(question: "Who played the character of Tony Soprano in the TV show 'The Sopranos'?", answer: "James Gandolfini", category: .television),
        Trivia(question: "Which TV show features characters named Homer, Marge, Bart, Lisa, and Maggie?", answer: "The Simpsons", category: .television),
        Trivia(question: "Who is the creator of the TV series 'The Office'?", answer: "Greg Daniels", category: .television),
        Trivia(question: "What is the name of the fictional continent in 'Game of Thrones'?", answer: "Westeros", category: .television),
        Trivia(question: "Who played the character of Don Draper in the TV show 'Mad Men'?", answer: "Jon Hamm", category: .television),
        Trivia(question: "Which TV show is set in the fictional town of Springfield?", answer: "The Simpsons", category: .television),
        Trivia(question: "Who is the host of the TV show 'The Late Show'?", answer: "Stephen Colbert", category: .television),
        Trivia(question: "In 'Breaking Bad', what is the street name of Walter White's alter ego?", answer: "Heisenberg", category: .television),
        Trivia(question: "Which TV show is set in the fictional town of Hawkins?", answer: "Stranger Things", category: .television),
        Trivia(question: "Who played the character of Michael Scott in the TV show 'The Office'?", answer: "Steve Carell", category: .television),
        Trivia(question: "Which TV show features characters named Carrie, Miranda, Charlotte, and Samantha?", answer: "Sex and the City", category: .television),
        Trivia(question: "Who is the host of the TV show 'The Tonight Show'?", answer: "Jimmy Fallon", category: .television),
        Trivia(question: "In 'Friends', what is the name of Ross and Rachel's daughter?", answer: "Emma", category: .television),
        Trivia(question: "Which TV show features a character named Barney Stinson?", answer: "How I Met Your Mother", category: .television),
        Trivia(question: "Who is the creator of the TV series 'Breaking Bad'?", answer: "Vince Gilligan", category: .television),
        Trivia(question: "In 'Game of Thrones', who is known as 'The Mother of Dragons'?", answer: "Daenerys Targaryen", category: .television),
        Trivia(question: "Which TV show features a character named Dexter Morgan?", answer: "Dexter", category: .television),
        Trivia(question: "Who is the host of the TV show 'Saturday Night Live'?", answer: "Lorne Michaels", category: .television),
        Trivia(question: "In 'The Office', what is the name of the fictional paper company where the characters work?", answer: "Dunder Mifflin", category: .television),
        Trivia(question: "Which TV show features a character named Carrie Mathison?", answer: "Homeland", category: .television),
        Trivia(question: "Who is the creator of the TV series 'Friends'?", answer: "David Crane and Marta Kauffman", category: .television),
        Trivia(question: "In 'Stranger Things', what is the name of Eleven's biological father?", answer: "Terry Ives", category: .television),
        Trivia(question: "Which TV show features a character named Phil Dunphy?", answer: "Modern Family", category: .television),
        Trivia(question: "Who is the creator of the TV series 'The Simpsons'?", answer: "Matt Groening", category: .television),
        Trivia(question: "In 'Breaking Bad', what is the name of Jesse Pinkman's friend and business partner?", answer: "Walter White", category: .television),
        Trivia(question: "Which TV show features a character named Omar Little?", answer: "The Wire", category: .television),
        Trivia(question: "Who is the host of the TV show 'Jeopardy!'?", answer: "Alex Trebek", category: .television),
        Trivia(question: "In 'Game of Thrones', who is Jon Snow's biological mother?", answer: "Lyanna Stark", category: .television),
        Trivia(question: "Which TV show features a character named Arya Stark?", answer: "Game of Thrones", category: .television),
        Trivia(question: "Who is the creator of the TV series 'The Walking Dead'?", answer: "Frank Darabont", category: .television),
        Trivia(question: "In 'Friends', what is the name of Joey's stuffed penguin?", answer: "Hugsy", category: .television),
        Trivia(question: "Which TV show features a character named Nucky Thompson?", answer: "Boardwalk Empire", category: .television),
        Trivia(question: "Who is the host of the TV show 'Wheel of Fortune'?", answer: "Pat Sajak", category: .television),
        Trivia(question: "In 'Breaking Bad', what is the name of Gus Fring's fast-food chain?", answer: "Los Pollos Hermanos", category: .television),
        Trivia(question: "Which TV show features a character named Tony Stark?", answer: "Iron Man: Armored Adventures", category: .television),
        Trivia(question: "Who is the creator of the TV series 'Lost'?", answer: "J.J. Abrams, Damon Lindelof, and Jeffrey Lieber", category: .television),
        Trivia(question: "In 'The Office', what is the name of Dwight Schrute's cousin, whom he claims to have made up?", answer: "Mose", category: .television),
        Trivia(question: "Which TV show features a character named Jack Bauer?", answer: "24", category: .television),
        Trivia(question: "Who is the host of the TV show 'The Daily Show'?", answer: "Trevor Noah", category: .television),
        Trivia(question: "In 'Friends', what is the name of Phoebe's twin sister?", answer: "Ursula", category: .television),
        Trivia(question: "Which TV show features characters named Sheldon, Leonard, and Penny?", answer: "The Big Bang Theory", category: .television),
        Trivia(question: "Who is the creator of the TV series 'Friends'?", answer: "David Crane and Marta Kauffman", category: .television),
        Trivia(question: "In 'Breaking Bad', what is the street name of Jesse Pinkman's character?", answer: "Cap'n Cook", category: .television),
        Trivia(question: "Which TV show features a character named Olivia Pope?", answer: "Scandal", category: .television),
        Trivia(question: "Who is the creator of the TV series 'Grey's Anatomy'?", answer: "Shonda Rhimes", category: .television),
        Trivia(question: "In 'The Office', what is the name of Jim and Pam's first child?", answer: "Cecelia", category: .television),
        Trivia(question: "Which TV show features a character named Harvey Specter?", answer: "Suits", category: .television),
        Trivia(question: "Who is the creator of the TV series 'House of Cards'?", answer: "Beau Willimon", category: .television),
        Trivia(question: "In 'Friends', what is the name of Ross's pet monkey?", answer: "Marcel", category: .television),
        Trivia(question: "Which TV show features characters named Meredith Grey and Derek Shepherd?", answer: "Grey's Anatomy", category: .television),
        Trivia(question: "Who is the creator of the TV series 'The West Wing'?", answer: "Aaron Sorkin", category: .television),
        Trivia(question: "In 'Breaking Bad', what is the name of the car wash owned by Walt and Skyler White?", answer: "A1A Car Wash", category: .television),
        Trivia(question: "Which TV show features a character named Dexter Morgan?", answer: "Dexter", category: .television),
        Trivia(question: "Who is the creator of the TV series 'Veep'?", answer: "Armando Iannucci", category: .television),
        Trivia(question: "In 'The Office', what is the name of Michael Scott's self-made holiday?", answer: "Scott's Tots", category: .television),
        Trivia(question: "Which TV show features a character named Leslie Knope?", answer: "Parks and Recreation", category: .television),
        Trivia(question: "Who is the creator of the TV series 'Arrested Development'?", answer: "Mitchell Hurwitz", category: .television),
        Trivia(question: "In 'Friends', what is the name of Chandler's job?", answer: "Statistical Analysis and Data Reconfiguration", category: .television),
        Trivia(question: "Which TV show features characters named Carrie Bradshaw and Mr. Big?", answer: "Sex and the City", category: .television),
        Trivia(question: "Who is the creator of the TV series 'The Crown'?", answer: "Peter Morgan", category: .television),
        Trivia(question: "In 'Breaking Bad', what is the name of Gus Fring's fast-food chain?", answer: "Los Pollos Hermanos", category: .television),
        Trivia(question: "Which TV show features a character named Michael Bluth?", answer: "Arrested Development", category: .television),
        Trivia(question: "Who is the creator of the TV series 'The Good Place'?", answer: "Michael Schur", category: .television),
        Trivia(question: "In 'The Office', what is the name of Dwight Schrute's beet farm?", answer: "Schrute Farms", category: .television),
        Trivia(question: "Which TV show features characters named Frank Underwood and Claire Underwood?", answer: "House of Cards", category: .television),
        Trivia(question: "Who is the creator of the TV series 'The Big Bang Theory'?", answer: "Chuck Lorre and Bill Prady", category: .television),
        Trivia(question: "In 'Friends', what is the name of Joey's stuffed penguin?", answer: "Hugsy", category: .television),
        Trivia(question: "Which TV show features a character named Michael Scott?", answer: "The Office", category: .television),
        Trivia(question: "Who is the creator of the TV series 'Lost'?", answer: "J.J. Abrams, Damon Lindelof, and Jeffrey Lieber", category: .television),
        Trivia(question: "In 'Breaking Bad', what is the name of the methamphetamine produced by Walter White?", answer: "Blue Sky", category: .television),
        Trivia(question: "Which TV show features a character named Carrie Mathison?", answer: "Homeland", category: .television),
        Trivia(question: "Who is the creator of the TV series 'Stranger Things'?", answer: "The Duffer Brothers", category: .television),
        Trivia(question: "In 'Friends', what is the name of the coffee shop where the characters often hang out?", answer: "Central Perk", category: .television),
        Trivia(question: "Which TV show features characters named Ross Poldark and Demelza Carne?", answer: "Poldark", category: .television),
        Trivia(question: "Who is the creator of the TV series 'Fargo'?", answer: "Noah Hawley", category: .television),
        Trivia(question: "In 'The Office', what is the name of the paper company that acquires Dunder Mifflin?", answer: "Sabre", category: .television),
        Trivia(question: "Which TV show features a character named Daenerys Targaryen?", answer: "Game of Thrones", category: .television),
        Trivia(question: "Who is the creator of the TV series 'Mr. Robot'?", answer: "Sam Esmail", category: .television),
        Trivia(question: "In 'Friends', what is the name of Ross's second wife?", answer: "Emily", category: .television),
        Trivia(question: "Which TV show features characters named Chandler, Joey, and Monica?", answer: "Friends", category: .television),
        Trivia(question: "Who played the character of Walter White in the TV show 'Breaking Bad'?", answer: "Bryan Cranston", category: .television),
        Trivia(question: "Which TV show features characters named Sheldon, Leonard, and Penny?", answer: "The Big Bang Theory", category: .television),
        Trivia(question: "Who is the primary antagonist in the TV series 'Game of Thrones'?", answer: "Night King", category: .television),
        Trivia(question: "In 'The Simpsons', what is the name of the bartender at Moe's Tavern?", answer: "Moe Szyslak", category: .television),
        Trivia(question: "Which TV show features characters named Ross Geller and Rachel Green?", answer: "Friends", category: .television),
        Trivia(question: "Who played the character of Tyrion Lannister in the TV show 'Game of Thrones'?", answer: "Peter Dinklage", category: .television),
        Trivia(question: "Which TV show features characters named Michael Scott and Dwight Schrute?", answer: "The Office", category: .television),
        Trivia(question: "In 'Stranger Things', what is the name of the government laboratory?", answer: "Hawkins National Laboratory", category: .television),
        Trivia(question: "Which TV show features characters named Carrie Bradshaw and Samantha Jones?", answer: "Sex and the City", category: .television),
        Trivia(question: "Who played the character of Olivia Pope in the TV show 'Scandal'?", answer: "Kerry Washington", category: .television),
        Trivia(question: "In 'Breaking Bad', what is the nickname of the drug lord Gustavo Fring?", answer: "Gus", category: .television),
        Trivia(question: "Which TV show features characters named Walter White and Jesse Pinkman?", answer: "Breaking Bad", category: .television),
        Trivia(question: "Who played the character of Carrie Mathison in the TV show 'Homeland'?", answer: "Claire Danes", category: .television),
        Trivia(question: "In 'The Office', what is the name of the company that acquires Dunder Mifflin?", answer: "Sabre", category: .television),
        Trivia(question: "Which TV show features characters named Tony Soprano and Carmela Soprano?", answer: "The Sopranos", category: .television),
        Trivia(question: "Who played the character of Phil Dunphy in the TV show 'Modern Family'?", answer: "Ty Burrell", category: .television),
        Trivia(question: "In 'Game of Thrones', what is the name of the currency used in Westeros?", answer: "Gold Dragon", category: .television),
        Trivia(question: "Which TV show features characters named Homer Simpson and Marge Simpson?", answer: "The Simpsons", category: .television),
        Trivia(question: "Who played the character of Michael Bluth in the TV show 'Arrested Development'?", answer: "Jason Bateman", category: .television),
        Trivia(question: "In 'Friends', what is the name of Phoebe Buffay's twin sister?", answer: "Ursula Buffay", category: .television),
        Trivia(question: "Which TV show features characters named Dexter Morgan and Debra Morgan?", answer: "Dexter", category: .television),
        Trivia(question: "Who played the character of Leslie Knope in the TV show 'Parks and Recreation'?", answer: "Amy Poehler", category: .television),
        Trivia(question: "In 'Breaking Bad', what is the name of the chemical used to dissolve bodies?", answer: "Hydrofluoric Acid", category: .television),
        Trivia(question: "Which TV show features characters named Jack Shephard and Kate Austen?", answer: "Lost", category: .television),
        Trivia(question: "Who played the character of Walter White in the TV show 'Breaking Bad'?", answer: "Bryan Cranston", category: .television),
        Trivia(question: "In 'Stranger Things', what is the name of the alternate dimension?", answer: "The Upside Down", category: .television),
        Trivia(question: "Which TV show features characters named Meredith Grey and Derek Shepherd?", answer: "Grey's Anatomy", category: .television),
        Trivia(question: "Who played the character of Tony Soprano in the TV show 'The Sopranos'?", answer: "James Gandolfini", category: .television),
        Trivia(question: "In 'The Office', what is the name of the company that acquires Dunder Mifflin?", answer: "Sabre", category: .television),
        Trivia(question: "Which TV show features characters named Sheldon Cooper and Amy Farrah Fowler?", answer: "The Big Bang Theory", category: .television),
        Trivia(question: "Who played the character of Olivia Pope in the TV show 'Scandal'?", answer: "Kerry Washington", category: .television),
        Trivia(question: "In 'Breaking Bad', what is the street name of Jesse Pinkman's character?", answer: "Cap'n Cook", category: .television),
        Trivia(question: "Which TV show features characters named Michael Scott and Dwight Schrute?", answer: "The Office", category: .television),
        Trivia(question: "Who is the creator of the TV series 'Grey's Anatomy'?", answer: "Shonda Rhimes", category: .television),
        Trivia(question: "In 'Stranger Things', what is the name of the government laboratory?", answer: "Hawkins National Laboratory", category: .television),
        Trivia(question: "Which TV show features characters named Carrie Bradshaw and Samantha Jones?", answer: "Sex and the City", category: .television),
        Trivia(question: "Who played the character of Olivia Pope in the TV show 'Scandal'?", answer: "Kerry Washington", category: .television),
        Trivia(question: "In 'Breaking Bad', what is the nickname of the drug lord Gustavo Fring?", answer: "Gus", category: .television),
        Trivia(question: "Which TV show features characters named Walter White and Jesse Pinkman?", answer: "Breaking Bad", category: .television),
        Trivia(question: "Who played the character of Carrie Mathison in the TV show 'Homeland'?", answer: "Claire Danes", category: .television),
        Trivia(question: "In 'The Office', what is the name of the company that acquires Dunder Mifflin?", answer: "Sabre", category: .television),
        Trivia(question: "Which TV show features characters named Tony Soprano and Carmela Soprano?", answer: "The Sopranos", category: .television),
        Trivia(question: "Who played the character of Phil Dunphy in the TV show 'Modern Family'?", answer: "Ty Burrell", category: .television),
        Trivia(question: "In 'Game of Thrones', what is the name of the currency used in Westeros?", answer: "Gold Dragon", category: .television),
        Trivia(question: "Which TV show features characters named Homer Simpson and Marge Simpson?", answer: "The Simpsons", category: .television),
    ]
    
    
    let movieQuestions: [Trivia] = [
        Trivia(question: "Who directed the movie 'The Social Network'?", answer: "David Fincher", category: .movies),
        Trivia(question: "What is the name of the robot in the movie 'Interstellar'?", answer: "TARS", category: .movies),
        Trivia(question: "Who played the character of Hannibal Lecter in the movie 'The Silence of the Lambs'?", answer: "Anthony Hopkins", category: .movies),
        Trivia(question: "Which film features a character named Rocky Balboa?", answer: "Rocky", category: .movies),
        Trivia(question: "Who directed the movie 'The Grand Budapest Hotel'?", answer: "Wes Anderson", category: .movies),
        Trivia(question: "What is the name of the main character in the 'Mad Max' series?", answer: "Max Rockatansky", category: .movies),
        Trivia(question: "Who played the lead role in the movie 'Goodfellas'?", answer: "Ray Liotta", category: .movies),
        Trivia(question: "Which movie features a character named Ellen Ripley?", answer: "Aliens", category: .movies),
        Trivia(question: "Who directed the movie 'Blade Runner'?", answer: "Ridley Scott", category: .movies),
        Trivia(question: "What is the name of the artificial intelligence in 'Ex Machina'?", answer: "Ava", category: .movies),
        Trivia(question: "Who played the character of Tony Montana in the movie 'Scarface'?", answer: "Al Pacino", category: .movies),
        Trivia(question: "Which film won the Academy Award for Best Animated Feature in 2019?", answer: "Toy Story 4", category: .movies),
        Trivia(question: "Who directed the movie 'The Revenant'?", answer: "Alejandro González Iñárritu", category: .movies),
        Trivia(question: "What is the name of the main character in the 'Die Hard' series?", answer: "John McClane", category: .movies),
        Trivia(question: "Who played the character of Sarah Connor in the movie 'Terminator 2: Judgment Day'?", answer: "Linda Hamilton", category: .movies),
        Trivia(question: "Which movie features a character named Neo?", answer: "The Matrix", category: .movies),
        Trivia(question: "Who directed the movie 'The Departed'?", answer: "Martin Scorsese", category: .movies),
        Trivia(question: "What is the name of the character played by Brad Pitt in the movie 'Fight Club'?", answer: "Tyler Durden", category: .movies),
        Trivia(question: "Who played the character of 'The Joker' in the movie 'The Dark Knight'?", answer: "Heath Ledger", category: .movies),
        Trivia(question: "Which film features a character named Atticus Finch?", answer: "To Kill a Mockingbird", category: .movies),
        Trivia(question: "Who directed the movie 'Taxi Driver'?", answer: "Martin Scorsese", category: .movies),
        Trivia(question: "What is the name of the boy who can see dead people in the movie 'The Sixth Sense'?", answer: "Cole Sear", category: .movies),
        Trivia(question: "Who played the character of James Bond in 'Goldfinger'?", answer: "Sean Connery", category: .movies),
        Trivia(question: "Which film won the Academy Award for Best Picture in 2008?", answer: "Slumdog Millionaire", category: .movies),
        Trivia(question: "Who directed the movie 'The Godfather: Part II'?", answer: "Francis Ford Coppola", category: .movies),
        Trivia(question: "What is the name of the high school in the movie 'Grease'?", answer: "Rydell High", category: .movies),
        Trivia(question: "Who played the character of Gollum in 'The Lord of the Rings' trilogy?", answer: "Andy Serkis", category: .movies),
        Trivia(question: "Which movie features a character named Jack Dawson?", answer: "Titanic", category: .movies),
        Trivia(question: "Who directed the movie 'The Sound of Music'?", answer: "Robert Wise", category: .movies),
        Trivia(question: "What is the name of the protagonist in 'The Shining'?", answer: "Jack Torrance", category: .movies),
        Trivia(question: "Who played the character of Maximus in the movie 'Gladiator'?", answer: "Russell Crowe", category: .movies),
        Trivia(question: "Which film features a character named Danny Ocean?", answer: "Ocean's Eleven", category: .movies),
        Trivia(question: "Who directed the movie 'The Exorcist'?", answer: "William Friedkin", category: .movies),
        Trivia(question: "What is the name of the alien in the movie 'E.T. the Extra-Terrestrial'?", answer: "E.T.", category: .movies),
        Trivia(question: "Who played the lead role in the movie 'The Truman Show'?", answer: "Jim Carrey", category: .movies),
        Trivia(question: "Which movie features a character named Indiana Jones?", answer: "Indiana Jones and the Last Crusade", category: .movies),
        Trivia(question: "Who directed the movie '2001: A Space Odyssey'?", answer: "Stanley Kubrick", category: .movies),
        Trivia(question: "What is the name of the king in 'The Lion King'?", answer: "Mufasa", category: .movies),
        Trivia(question: "Who played the character of Clarice Starling in the movie 'The Silence of the Lambs'?", answer: "Jodie Foster", category: .movies),
        Trivia(question: "Which film features a character named Rick Blaine?", answer: "Casablanca", category: .movies),
        Trivia(question: "Who directed the movie 'Citizen Kane'?", answer: "Orson Welles", category: .movies),
        Trivia(question: "What is the name of the dinosaur in 'Jurassic Park' that spits poison?", answer: "Dilophosaurus", category: .movies),
        Trivia(question: "Who played the character of Alex DeLarge in the movie 'A Clockwork Orange'?", answer: "Malcolm McDowell", category: .movies),
        Trivia(question: "Which movie features a character named James Bond?", answer: "Dr. No", category: .movies),
        Trivia(question: "Who directed the movie 'Apocalypse Now'?", answer: "Francis Ford Coppola", category: .movies),
        Trivia(question: "What is the name of the character played by Johnny Depp in the 'Edward Scissorhands'?", answer: "Edward", category: .movies),
        Trivia(question: "Who played the character of Norma Desmond in the movie 'Sunset Boulevard'?", answer: "Gloria Swanson", category: .movies),
        Trivia(question: "Who directed the movie 'Inception'?", answer: "Christopher Nolan", category: .movies),
        Trivia(question: "What year was the first 'Toy Story' movie released?", answer: "1995", category: .movies),
        Trivia(question: "Which film won the Academy Award for Best Picture in 2020?", answer: "Parasite", category: .movies),
        Trivia(question: "What is the highest-grossing film of all time (not adjusted for inflation)?", answer: "Avengers: Endgame", category: .movies),
        Trivia(question: "Who directed the movie 'Jurassic Park'?", answer: "Steven Spielberg", category: .movies),
        Trivia(question: "Which actor portrayed James Bond in the movie 'Casino Royale'?", answer: "Daniel Craig", category: .movies),
        Trivia(question: "What is the name of the dragon in 'Shrek'?", answer: "Donkey", category: .movies),
        Trivia(question: "Who played Neo in 'The Matrix' trilogy?", answer: "Keanu Reeves", category: .movies),
        Trivia(question: "What is the name of the hobbit played by Elijah Wood in 'The Lord of the Rings' trilogy?", answer: "Frodo Baggins", category: .movies),
        Trivia(question: "Who directed the movie 'Pulp Fiction'?", answer: "Quentin Tarantino", category: .movies),
        Trivia(question: "What is the highest-grossing animated film of all time?", answer: "Frozen II", category: .movies),
        Trivia(question: "Which movie features a character named Tyler Durden?", answer: "Fight Club", category: .movies),
        Trivia(question: "What is the name of the clownfish in 'Finding Nemo'?", answer: "Nemo", category: .movies),
        Trivia(question: "Who played the character of Captain Jack Sparrow in the 'Pirates of the Caribbean' series?", answer: "Johnny Depp", category: .movies),
        Trivia(question: "Which film won the first Academy Award for Best Picture?", answer: "Wings", category: .movies),
        Trivia(question: "Who directed the movie 'The Shawshank Redemption'?", answer: "Frank Darabont", category: .movies),
        Trivia(question: "What is the name of the spaceship in the movie 'Alien'?", answer: "Nostromo", category: .movies),
        Trivia(question: "Who provided the voice for Dory in the movie 'Finding Nemo'?", answer: "Ellen DeGeneres", category: .movies),
        Trivia(question: "In the movie 'The Wizard of Oz', what does the witch want from Dorothy?", answer: "Her Ruby Slippers", category: .movies),
        Trivia(question: "Who played the character of Forrest Gump in the movie 'Forrest Gump'?", answer: "Tom Hanks", category: .movies),
        Trivia(question: "What is the name of the artificial intelligence in '2001: A Space Odyssey'?", answer: "HAL 9000", category: .movies),
        Trivia(question: "Which actress portrayed Hermione Granger in the 'Harry Potter' series?", answer: "Emma Watson", category: .movies),
        Trivia(question: "Who directed the movie 'The Dark Knight'?", answer: "Christopher Nolan", category: .movies),
        Trivia(question: "What is the highest-grossing film directed by Steven Spielberg?", answer: "Jurassic Park", category: .movies),
        Trivia(question: "Who played the lead role in the movie 'Gladiator'?", answer: "Russell Crowe", category: .movies),
        Trivia(question: "What is the name of the character played by Leonardo DiCaprio in 'Titanic'?", answer: "Jack Dawson", category: .movies),
        Trivia(question: "Who provided the voice for the character of Shrek in the movie 'Shrek'?", answer: "Mike Myers", category: .movies),
        Trivia(question: "What is the name of the school of witchcraft and wizardry in the 'Harry Potter' series?", answer: "Hogwarts", category: .movies),
        Trivia(question: "Who directed the movie 'Avatar'?", answer: "James Cameron", category: .movies),
        Trivia(question: "Which film features a character named Indiana Jones?", answer: "Raiders of the Lost Ark", category: .movies),
        Trivia(question: "What is the name of the snowman in Disney's 'Frozen'?", answer: "Olaf", category: .movies),
        Trivia(question: "Who played the role of Edward Scissorhands in the movie of the same name?", answer: "Johnny Depp", category: .movies),
        Trivia(question: "What is the name of the town where 'The Simpsons' live?", answer: "Springfield", category: .movies),
        Trivia(question: "Who directed the movie 'Forrest Gump'?", answer: "Robert Zemeckis", category: .movies),
        Trivia(question: "What is the name of the robot in the movie 'WALL-E'?", answer: "WALL-E", category: .movies),
        Trivia(question: "Who played the character of Tony Stark in the 'Iron Man' trilogy?", answer: "Robert Downey Jr.", category: .movies),
        Trivia(question: "Which film features a character named Ellen Ripley?", answer: "Alien", category: .movies),
        Trivia(question: "What is the name of the village in 'The Lord of the Rings' trilogy where Frodo and his friends begin their journey?", answer: "Hobbiton", category: .movies),
        Trivia(question: "Who played the character of Vito Corleone in the movie 'The Godfather'?", answer: "Marlon Brando", category: .movies),
        Trivia(question: "What is the name of the giant shark in the movie 'Jaws'?", answer: "Bruce", category: .movies),
        Trivia(question: "Who directed the movie 'The Silence of the Lambs'?", answer: "Jonathan Demme", category: .movies),
        Trivia(question: "What is the name of the computer program in the movie 'The Matrix'?", answer: "Agent Smith", category: .movies),
        Trivia(question: "Who played the character of Michael Corleone in 'The Godfather' trilogy?", answer: "Al Pacino", category: .movies),
        Trivia(question: "Which film features a character named Clarice Starling?", answer: "The Silence of the Lambs", category: .movies),
        Trivia(question: "Who provided the voice for Sully in the movie 'Monsters, Inc.'?", answer: "John Goodman", category: .movies),
        Trivia(question: "In the movie 'The Lion King', who is Simba's father?", answer: "Mufasa", category: .movies),
        Trivia(question: "Who directed the movie 'E.T. the Extra-Terrestrial'?", answer: "Steven Spielberg", category: .movies),
        Trivia(question: "What is the name of the character played by Johnny Depp in the 'Pirates of the Caribbean' series?", answer: "Captain Jack Sparrow", category: .movies),
        Trivia(question: "Which movie features the song 'Let It Go'?", answer: "Frozen", category: .movies),
        Trivia(question: "Who played the role of Hermione Granger in the 'Harry Potter' series?", answer: "Emma Watson", category: .movies),
        Trivia(question: "What is the name of the protagonist in 'The Hunger Games' series?", answer: "Katniss Everdeen", category: .movies),
        Trivia(question: "Who directed the movie 'The Breakfast Club'?", answer: "John Hughes", category: .movies),
        Trivia(question: "What is the name of the lead character in the movie 'The Graduate'?", answer: "Benjamin Braddock", category: .movies),
        Trivia(question: "Who played the character of Rick Deckard in the movie 'Blade Runner'?", answer: "Harrison Ford", category: .movies),
        Trivia(question: "Which film features a character named Forrest Gump?", answer: "Forrest Gump", category: .movies),
        Trivia(question: "Who directed the movie 'Schindler's List'?", answer: "Steven Spielberg", category: .movies),
        Trivia(question: "What is the name of the character played by Anthony Perkins in 'Psycho'?", answer: "Norman Bates", category: .movies),
        Trivia(question: "Who played the character of Ellen Ripley in the movie 'Alien'?", answer: "Sigourney Weaver", category: .movies),
        Trivia(question: "Which movie features a character named Ferris Bueller?", answer: "Ferris Bueller's Day Off", category: .movies),
        Trivia(question: "Who directed the movie 'The Godfather: Part III'?", answer: "Francis Ford Coppola", category: .movies),
        Trivia(question: "What is the name of the dog in the movie 'Wizard of Oz'?", answer: "Toto", category: .movies),
        Trivia(question: "Who played the character of Norman Bates in the movie 'Psycho'?", answer: "Anthony Perkins", category: .movies),
        Trivia(question: "Which film won the Academy Award for Best Picture in 2017?", answer: "Moonlight", category: .movies),
        Trivia(question: "Who directed the movie 'The Matrix'?", answer: "The Wachowskis", category: .movies),
        Trivia(question: "What is the name of the giant ape in the movie 'King Kong'?", answer: "Kong", category: .movies),
        Trivia(question: "Who played the character of Don Vito Corleone in the movie 'The Godfather'?", answer: "Marlon Brando", category: .movies),
        Trivia(question: "Which movie features a character named Tony Stark?", answer: "Iron Man", category: .movies),
        Trivia(question: "Who directed the movie 'The Avengers'?", answer: "Joss Whedon", category: .movies),
        Trivia(question: "What is the name of the character played by Vivien Leigh in 'Gone with the Wind'?", answer: "Scarlett O'Hara", category: .movies),
        Trivia(question: "Who played the lead role in the movie 'The Shawshank Redemption'?", answer: "Tim Robbins", category: .movies),
        Trivia(question: "Which film features a character named Darth Vader?", answer: "Star Wars: Episode IV - A New Hope", category: .movies),
        Trivia(question: "Who directed the movie 'Gone with the Wind'?", answer: "Victor Fleming", category: .movies),
        Trivia(question: "What is the name of the high school in the movie 'Mean Girls'?", answer: "North Shore High School", category: .movies),
        Trivia(question: "Who played the character of James Bond in 'GoldenEye'?", answer: "Pierce Brosnan", category: .movies),
        Trivia(question: "Which movie features a character named Harry Potter?", answer: "Harry Potter and the Sorcerer's Stone", category: .movies),
        Trivia(question: "Who directed the movie 'Back to the Future'?", answer: "Robert Zemeckis", category: .movies),
        Trivia(question: "What is the name of the character played by Audrey Hepburn in 'Breakfast at Tiffany's'?", answer: "Holly Golightly", category: .movies),
        Trivia(question: "Who played the character of Indiana Jones in the movie 'Raiders of the Lost Ark'?", answer: "Harrison Ford", category: .movies),
        Trivia(question: "Which film won the Academy Award for Best Picture in 1994?", answer: "Forrest Gump", category: .movies),
        Trivia(question: "Who directed the movie 'Casablanca'?", answer: "Michael Curtiz", category: .movies),
        Trivia(question: "What is the name of the car in the movie 'Smokey and the Bandit'?", answer: "Trans Am", category: .movies),
        Trivia(question: "Who played the character of Dr. Hannibal Lecter in the movie 'Hannibal'?", answer: "Anthony Hopkins", category: .movies),
        Trivia(question: "Which movie features a character named Jack Sparrow?", answer: "Pirates of the Caribbean: The Curse of the Black Pearl", category: .movies),
        Trivia(question: "Who directed the movie 'The Lion King'?", answer: "Roger Allers and Rob Minkoff", category: .movies),
        Trivia(question: "What is the name of the assassin in the movie 'Kill Bill'?", answer: "Beatrix Kiddo", category: .movies),
        Trivia(question: "Who played the character of Batman in the movie 'The Dark Knight Rises'?", answer: "Christian Bale", category: .movies),
        Trivia(question: "Which film features a character named Princess Leia?", answer: "Star Wars: Episode IV - A New Hope", category: .movies),
        Trivia(question: "Who directed the movie 'The Green Mile'?", answer: "Frank Darabont", category: .movies),
        Trivia(question: "What is the name of the character played by Matt Damon in the movie 'Good Will Hunting'?", answer: "Will Hunting", category: .movies),
        Trivia(question: "Who played the character of Keyser Söze in the movie 'The Usual Suspects'?", answer: "Kevin Spacey", category: .movies),
        Trivia(question: "Which movie features a character named Jack Torrance?", answer: "The Shining", category: .movies),
        Trivia(question: "Who directed the movie 'The Terminator'?", answer: "James Cameron", category: .movies),
        Trivia(question: "What is the name of the character played by Harrison Ford in the 'Indiana Jones' series?", answer: "Indiana Jones", category: .movies),
        Trivia(question: "Who played the lead role in the movie 'The Godfather'?", answer: "Al Pacino", category: .movies),
        Trivia(question: "Which film won the Academy Award for Best Picture in 1980?", answer: "Ordinary People", category: .movies),
        Trivia(question: "Who directed the movie 'Lawrence of Arabia'?", answer: "David Lean", category: .movies),
        Trivia(question: "What is the name of the ship in the movie 'Titanic'?", answer: "RMS Titanic", category: .movies)
    ]
    
    let presidentQuestions: [Trivia] = [
        Trivia(question: "Who was the first President of the United States?", answer: "George Washington", category: .presidents),
        Trivia(question: "Which President signed the Emancipation Proclamation?", answer: "Abraham Lincoln", category: .presidents),
        Trivia(question: "Who was the only President to serve more than two terms?", answer: "Franklin D. Roosevelt", category: .presidents),
        Trivia(question: "Which President is known as the 'Father of the Constitution'?", answer: "James Madison", category: .presidents),
        Trivia(question: "Who was the President during the Civil War?", answer: "Abraham Lincoln", category: .presidents),
        Trivia(question: "Which President is famous for the Louisiana Purchase?", answer: "Thomas Jefferson", category: .presidents),
        Trivia(question: "Who was the first President to be impeached?", answer: "Andrew Johnson", category: .presidents),
        Trivia(question: "Which President is known for the 'New Deal'?", answer: "Franklin D. Roosevelt", category: .presidents),
        Trivia(question: "Who was the first President born in the United States?", answer: "Martin Van Buren", category: .presidents),
        Trivia(question: "Which President was a famous general in World War II before becoming President?", answer: "Dwight D. Eisenhower", category: .presidents),
        Trivia(question: "Who was the only President to resign from office?", answer: "Richard Nixon", category: .presidents),
        Trivia(question: "Which President was in office during the Great Depression and World War II?", answer: "Franklin D. Roosevelt", category: .presidents),
        Trivia(question: "Who was the President during the Bay of Pigs invasion and the Cuban Missile Crisis?", answer: "John F. Kennedy", category: .presidents),
        Trivia(question: "Which President was responsible for the creation of the National Park Service?", answer: "Theodore Roosevelt", category: .presidents),
        Trivia(question: "Who was the first President to live in the White House?", answer: "John Adams", category: .presidents),
        Trivia(question: "Which President issued the 'Monroe Doctrine'?", answer: "James Monroe", category: .presidents),
        Trivia(question: "Who was the President during the Korean War?", answer: "Harry S. Truman", category: .presidents),
        Trivia(question: "Which President is associated with the Watergate scandal?", answer: "Richard Nixon", category: .presidents),
        Trivia(question: "Who was the only President to serve two non-consecutive terms?", answer: "Grover Cleveland", category: .presidents),
        Trivia(question: "Which President was responsible for the creation of Social Security?", answer: "Franklin D. Roosevelt", category: .presidents),
        Trivia(question: "Who was the President during the Mexican-American War?", answer: "James K. Polk", category: .presidents),
        Trivia(question: "Which President was known as 'Old Hickory'?", answer: "Andrew Jackson", category: .presidents),
        Trivia(question: "Who was the President during the War of 1812?", answer: "James Madison", category: .presidents),
        Trivia(question: "Which President signed the Civil Rights Act of 1964 into law?", answer: "Lyndon B. Johnson", category: .presidents),
        Trivia(question: "Who was the first President to be assassinated?", answer: "Abraham Lincoln", category: .presidents),
        Trivia(question: "Which President was in office during the Vietnam War?", answer: "Lyndon B. Johnson", category: .presidents),
        Trivia(question: "Who was the President during the Spanish-American War?", answer: "William McKinley", category: .presidents),
        Trivia(question: "Which President was known as 'The Great Communicator'?", answer: "Ronald Reagan", category: .presidents),
        Trivia(question: "Who was the first President to fly in an airplane while in office?", answer: "Franklin D. Roosevelt", category: .presidents),
        Trivia(question: "Which President appointed the first woman to the Supreme Court?", answer: "Ronald Reagan", category: .presidents),
        Trivia(question: "Who was the President during the Iranian hostage crisis?", answer: "Jimmy Carter", category: .presidents),
        Trivia(question: "Which President is known for the 'Square Deal'?", answer: "Theodore Roosevelt", category: .presidents),
        Trivia(question: "Who was the only President to serve as Chief Justice of the Supreme Court after leaving office?", answer: "William Howard Taft", category: .presidents),
        Trivia(question: "Which President was in office during the signing of the Treaty of Versailles, ending World War I?", answer: "Woodrow Wilson", category: .presidents),
        Trivia(question: "Who was the first President to be born a citizen of the United States?", answer: "Martin Van Buren", category: .presidents),
        Trivia(question: "Which President initiated the 'War on Poverty'?", answer: "Lyndon B. Johnson", category: .presidents),
        Trivia(question: "Who was the President during the stock market crash of 1929 and the beginning of the Great Depression?", answer: "Herbert Hoover", category: .presidents),
        Trivia(question: "Which President was known as 'The Trust Buster'?", answer: "Theodore Roosevelt", category: .presidents),
        Trivia(question: "Who was the President during the annexation of Texas?", answer: "James K. Polk", category: .presidents),
        Trivia(question: "Which President signed the Indian Removal Act, leading to the Trail of Tears?", answer: "Andrew Jackson", category: .presidents),
        Trivia(question: "Who was the President during the signing of the North American Free Trade Agreement (NAFTA)?", answer: "Bill Clinton", category: .presidents),
        Trivia(question: "Which President was in office during the Berlin Airlift?", answer: "Harry S. Truman", category: .presidents),
        Trivia(question: "Who was the President during the Spanish flu pandemic of 1918?", answer: "Woodrow Wilson", category: .presidents),
        Trivia(question: "Which President served as the commander-in-chief of the Continental Army during the American Revolutionary War?", answer: "George Washington", category: .presidents),
        Trivia(question: "Who was the only President to serve as a non-commissioned officer in the military?", answer: "Andrew Johnson", category: .presidents),
        Trivia(question: "Which President was known for the 'Great Society' domestic programs?", answer: "Lyndon B. Johnson", category: .presidents),
        Trivia(question: "Who was the President during the Apollo 11 moon landing?", answer: "Richard Nixon",category: .presidents),
        Trivia(question: "Who was the President during the Gulf War?", answer: "George H. W. Bush", category: .presidents),
        Trivia(question: "Which President was responsible for the creation of Medicare and Medicaid?", answer: "Lyndon B. Johnson", category: .presidents),
        Trivia(question: "Who was the President during the Cuban Revolution and the rise of Fidel Castro?", answer: "Dwight D. Eisenhower", category: .presidents),
        Trivia(question: "Which President was known for the 'Fourteen Points' plan for peace after World War I?", answer: "Woodrow Wilson", category: .presidents),
        Trivia(question: "Who was the President during the Oklahoma City bombing?", answer: "Bill Clinton", category: .presidents),
        Trivia(question: "Which President signed the Civil Rights Act of 1968, also known as the Fair Housing Act?", answer: "Lyndon B. Johnson", category: .presidents),
        Trivia(question: "Who was the President during the construction of the Berlin Wall?", answer: "John F. Kennedy", category: .presidents),
        Trivia(question: "Which President was in office during the September 11 terrorist attacks?", answer: "George W. Bush", category: .presidents),
        Trivia(question: "Who was the President during the first Persian Gulf War?", answer: "George H. W. Bush", category: .presidents),
        Trivia(question: "Which President was known as 'The Gipper'?", answer: "Ronald Reagan", category: .presidents),
        Trivia(question: "Who was the President during the Exxon Valdez oil spill?", answer: "George H. W. Bush", category: .presidents),
        Trivia(question: "Which President signed the Americans with Disabilities Act into law?", answer: "George H. W. Bush", category: .presidents),
        Trivia(question: "Who was the President during the Iran-Contra affair?", answer: "Ronald Reagan", category: .presidents),
        Trivia(question: "Which President was responsible for the establishment of the Environmental Protection Agency (EPA)?", answer: "Richard Nixon", category: .presidents),
        Trivia(question: "Who was the President during the signing of the North Atlantic Treaty Organization (NATO)?", answer: "Harry S. Truman", category: .presidents),
        Trivia(question: "Which President was in office during the signing of the Alaska and Hawaii statehood bills?", answer: "Dwight D. Eisenhower", category: .presidents),
        Trivia(question: "Who was the President during the Apollo 13 mission?", answer: "Richard Nixon", category: .presidents),
        Trivia(question: "Which President was known as 'The Great Communicator'?", answer: "Ronald Reagan", category: .presidents),
        Trivia(question: "Who was the President during the Suez Crisis?", answer: "Dwight D. Eisenhower", category: .presidents),
        Trivia(question: "Which President was responsible for the creation of the Department of Homeland Security?", answer: "George W. Bush", category: .presidents),
        Trivia(question: "Who was the President during the Cuban Missile Crisis?", answer: "John F. Kennedy", category: .presidents),
        Trivia(question: "Which President signed the Civil Rights Act of 1957 into law?", answer: "Dwight D. Eisenhower", category: .presidents),
        Trivia(question: "Who was the President during the Mexican-American War?", answer: "James K. Polk", category: .presidents),
        Trivia(question: "Which President was known for the 'Rough Riders' regiment in the Spanish-American War?", answer: "Theodore Roosevelt", category: .presidents),
        Trivia(question: "Who was the President during the Louisiana Purchase?", answer: "Thomas Jefferson", category: .presidents),
        Trivia(question: "Which President was in office during the signing of the Treaty of Guadalupe Hidalgo, ending the Mexican-American War?", answer: "James K. Polk", category: .presidents),
        Trivia(question: "Who was the President during the Whiskey Rebellion?", answer: "George Washington", category: .presidents),
        Trivia(question: "Which President was known as 'The Sage of Monticello'?", answer: "Thomas Jefferson", category: .presidents),
        Trivia(question: "Who was the President during the War of 1812?", answer: "James Madison", category: .presidents),
        Trivia(question: "Which President served as the Secretary of State under President George Washington?", answer: "Thomas Jefferson", category: .presidents),
        Trivia(question: "Who was the President during the signing of the Treaty of Paris, officially ending the American Revolutionary War?", answer: "George Washington", category: .presidents),
        Trivia(question: "Which President was known for the 'Trail of Tears'?", answer: "Andrew Jackson", category: .presidents),
        Trivia(question: "Who was the President during the Teapot Dome scandal?", answer: "Warren G. Harding", category: .presidents),
        Trivia(question: "Which President was responsible for the creation of the Federal Reserve System?", answer: "Woodrow Wilson", category: .presidents),
        Trivia(question: "Who was the President during the Panic of 1837?", answer: "Martin Van Buren", category: .presidents),
        Trivia(question: "Which President was known as 'The Accidental President'?", answer: "Gerald Ford", category: .presidents),
        Trivia(question: "Who was the President during the assassination of President Abraham Lincoln?", answer: "Andrew Johnson", category: .presidents),
        Trivia(question: "Which President was responsible for the Louisiana Purchase?", answer: "Thomas Jefferson", category: .presidents),
        Trivia(question: "Who was the President during the signing of the Declaration of Independence?", answer: "John Hancock (as President of the Continental Congress)", category: .presidents),
        Trivia(question: "Which President was known as 'The Man of the People'?", answer: "Andrew Jackson", category: .presidents),
        Trivia(question: "Who was the President during the Battle of Gettysburg?", answer: "Abraham Lincoln", category: .presidents),
        Trivia(question: "Which President was responsible for the annexation of Texas?", answer: "James K. Polk", category: .presidents),
        Trivia(question: "Who was the President during the signing of the Missouri Compromise?", answer: "James Monroe", category: .presidents),
        Trivia(question: "Which President was known as 'The Great Emancipator'?", answer: "Abraham Lincoln", category: .presidents),
        Trivia(question: "Who was the President during the signing of the Treaty of Versailles, ending World War I?", answer: "Woodrow Wilson", category: .presidents),
        Trivia(question: "Which President was responsible for the creation of the Interstate Highway System?", answer: "Dwight D. Eisenhower", category: .presidents),
        Trivia(question: "Who was the President during the Battle of the Alamo?", answer: "Andrew Jackson", category: .presidents),
        Trivia(question: "Which President was responsible for the creation of the National Aeronautics and Space Administration (NASA)?", answer: "Dwight D. Eisenhower", category: .presidents),
        Trivia(question: "Who was the President during the Cuban Revolution and the rise of Fidel Castro?", answer: "Dwight D. Eisenhower", category: .presidents),
        Trivia(question: "Which President signed the Treaty of Ghent, ending the War of 1812?", answer: "James Madison", category: .presidents),
        Trivia(question: "Who was the President during the signing of the Kansas-Nebraska Act?", answer: "Franklin Pierce", category: .presidents),
        Trivia(question: "Which President was in office during the 'Panic of 1893' economic depression?", answer: "Grover Cleveland", category: .presidents),
        Trivia(question: "Who was the President during the signing of the Treaty of Guadalupe Hidalgo, ending the Mexican-American War?", answer: "James K. Polk", category: .presidents),
        Trivia(question: "Which President was responsible for the creation of the Federal Trade Commission (FTC)?", answer: "Woodrow Wilson", category: .presidents),
        Trivia(question: "Who was the President during the signing of the Civil Rights Act of 1964?", answer: "Lyndon B. Johnson", category: .presidents),
        Trivia(question: "Which President was known as 'The Last of the Cocked Hats'?", answer: "James Monroe", category: .presidents),
        Trivia(question: "Who was the President during the 'Whiskey Rebellion'?", answer: "George Washington", category: .presidents),
        Trivia(question: "Which President was responsible for the creation of the Tennessee Valley Authority (TVA)?", answer: "Franklin D. Roosevelt", category: .presidents),
        Trivia(question: "Who was the President during the 'Panic of 1873' economic depression?", answer: "Ulysses S. Grant", category: .presidents),
        Trivia(question: "Which President was in office during the establishment of the National Labor Relations Board (NLRB)?", answer: "Franklin D. Roosevelt", category: .presidents),
        Trivia(question: "Who was the President during the signing of the Treaty of Paris, which ended the Spanish-American War?", answer: "William McKinley", category: .presidents),
        Trivia(question: "Which President was known as 'The Gentleman Boss'?", answer: "Chester A. Arthur", category: .presidents),
        Trivia(question: "Who was the President during the passage of the 13th Amendment, which abolished slavery?", answer: "Abraham Lincoln", category: .presidents),
        Trivia(question: "Which President was responsible for the creation of the Department of Veterans Affairs?", answer: "Ronald Reagan", category: .presidents),
        Trivia(question: "Who was the President during the signing of the Treaty of Kanagawa, which opened Japan to trade with the United States?", answer: "Millard Fillmore", category: .presidents),
        Trivia(question: "Which President was known as 'The Father of His Country'?", answer: "George Washington", category: .presidents),
        Trivia(question: "Who was the President during the signing of the Treaty of Portsmouth, ending the Russo-Japanese War?", answer: "Theodore Roosevelt", category: .presidents),
        Trivia(question: "Which President was responsible for the creation of the Department of Health and Human Services (HHS)?", answer: "Jimmy Carter", category: .presidents),
        Trivia(question: "Who was the President during the signing of the Treaty of Washington, which settled disputes between the United States and Great Britain after the Civil War?", answer: "Ulysses S. Grant", category: .presidents),
        Trivia(question: "Which President was known as 'The Sage of the White House'?", answer: "Grover Cleveland", category: .presidents),
        Trivia(question: "Who was the President during the passage of the 19th Amendment, which granted women the right to vote?", answer: "Woodrow Wilson", category: .presidents),
        Trivia(question: "Which President was responsible for the creation of the National Security Council (NSC)?", answer: "Harry S. Truman", category: .presidents),
        Trivia(question: "Who was the President during the signing of the Treaty of Paris, which ended the American Revolutionary War?", answer: "George Washington", category: .presidents),
        Trivia(question: "Which President was known as 'The Liberator'?", answer: "Abraham Lincoln", category: .presidents),
        Trivia(question: "Who was the President during the passage of the Indian Removal Act, leading to the Trail of Tears?", answer: "Andrew Jackson", category: .presidents),
        Trivia(question: "Which President was responsible for the creation of the Department of Defense (DoD)?", answer: "Harry S. Truman", category: .presidents),
        Trivia(question: "Who was the President during the signing of the Treaty of Guadalupe Hidalgo, ending the Mexican-American War?", answer: "James K. Polk", category: .presidents),
        Trivia(question: "Which President was known as 'The Hero of New Orleans'?", answer: "Andrew Jackson", category: .presidents),
        Trivia(question: "Who was the President during the signing of the Treaty of Fort Laramie, establishing Native American territories?", answer: "Ulysses S. Grant", category: .presidents),
        Trivia(question: "Which President was responsible for the creation of the United States Secret Service?", answer: "Abraham Lincoln", category: .presidents),
        Trivia(question: "Who was the President during the signing of the Treaty of Paris, which ended the Spanish-American War?", answer: "William McKinley", category: .presidents),
        Trivia(question: "Which President was known as 'The Dark Horse President'?", answer: "James K. Polk", category: .presidents),
        Trivia(question: "Who was the President during the passage of the Civil Rights Act of 1875?", answer: "Ulysses S. Grant", category: .presidents),
        Trivia(question: "Which President was responsible for the creation of the Department of Commerce and Labor?", answer: "Theodore Roosevelt", category: .presidents),
        Trivia(question: "Who was the President during the signing of the Treaty of Paris, which ended the American Revolutionary War?", answer: "George Washington", category: .presidents),
        Trivia(question: "Which President was known as 'The Last Whig President'?", answer: "Millard Fillmore", category: .presidents),
        Trivia(question: "Who was the President during the passage of the Kansas-Nebraska Act?", answer: "Franklin Pierce", category: .presidents)
    ]
    
    let usHistoryQuestions: [Trivia] = [
        Trivia(question: "Who was the first President of the United States?", answer: "George Washington", category: .usHistory),
        Trivia(question: "What year was the Declaration of Independence signed?", answer: "1776", category: .usHistory),
        Trivia(question: "Who was the President of the Confederate States during the American Civil War?", answer: "Jefferson Davis", category: .usHistory),
        Trivia(question: "What event led to the United States' entry into World War II?", answer: "Attack on Pearl Harbor", category: .usHistory),
        Trivia(question: "Who was the first woman to fly solo across the Atlantic Ocean?", answer: "Amelia Earhart", category: .usHistory),
        Trivia(question: "What was the period of tension between the United States and the Soviet Union called?", answer: "Cold War", category: .usHistory),
        Trivia(question: "Who was the main author of the United States Constitution?", answer: "James Madison", category: .usHistory),
        Trivia(question: "Which amendment to the US Constitution abolished slavery?", answer: "13th Amendment", category: .usHistory),
        Trivia(question: "Who invented the assembly line production system?", answer: "Henry Ford", category: .usHistory),
        Trivia(question: "What was the name of the first successful English colony in North America?", answer: "Jamestown", category: .usHistory),
        Trivia(question: "Who was the President of the United States during the Great Depression and World War II?", answer: "Franklin D. Roosevelt", category: .usHistory),
        Trivia(question: "Which Supreme Court case established the principle of judicial review?", answer: "Marbury v. Madison", category: .usHistory),
        Trivia(question: "Who was the leader of the American civil rights movement who advocated for nonviolent resistance?", answer: "Martin Luther King Jr.", category: .usHistory),
        Trivia(question: "What was the name of the ship that carried the Pilgrims to America in 1620?", answer: "Mayflower", category: .usHistory),
        Trivia(question: "Who served as President of the United States during the Cuban Missile Crisis?", answer: "John F. Kennedy", category: .usHistory),
        Trivia(question: "Which territory did the United States purchase from France in 1803?", answer: "Louisiana Territory", category: .usHistory),
        Trivia(question: "Who was the first European explorer to reach the Americas in 1492?", answer: "Christopher Columbus", category: .usHistory),
        Trivia(question: "Which US President signed the Emancipation Proclamation?", answer: "Abraham Lincoln", category: .usHistory),
        Trivia(question: "What was the name of the first successful English colony in North America?", answer: "Jamestown", category: .usHistory),
        Trivia(question: "Who was the President of the United States during the Civil War?", answer: "Abraham Lincoln", category: .usHistory),
        Trivia(question: "Which amendment to the US Constitution gave women the right to vote?", answer: "19th Amendment", category: .usHistory),
        Trivia(question: "Who was the commander-in-chief of the Continental Army during the American Revolutionary War?", answer: "George Washington", category: .usHistory),
        Trivia(question: "What was the name of the first permanent English settlement in North America?", answer: "Jamestown", category: .usHistory),
        Trivia(question: "Which US President is known for his leadership during the Civil Rights Movement and signed the Civil Rights Act of 1964?", answer: "Lyndon B. Johnson", category: .usHistory),
        Trivia(question: "Who was the first African American to serve on the United States Supreme Court?", answer: "Thurgood Marshall", category: .usHistory),
        Trivia(question: "What was the name of the movement to promote the production and sale of alcohol in the United States during the early 20th century?", answer: "Prohibition", category: .usHistory),
        Trivia(question: "Who was the President of the United States during the Mexican-American War?", answer: "James K. Polk", category: .usHistory),
        Trivia(question: "Which US President ordered the dropping of atomic bombs on Hiroshima and Nagasaki?", answer: "Harry S. Truman", category: .usHistory),
        Trivia(question: "Who was the first woman to be appointed to the United States Supreme Court?", answer: "Sandra Day O'Connor", category: .usHistory),
        Trivia(question: "What was the name of the economic program implemented by President Franklin D. Roosevelt to address the Great Depression?", answer: "New Deal", category: .usHistory),
        Trivia(question: "Who was the President of the Confederate States during the American Civil War?", answer: "Jefferson Davis", category: .usHistory),
        Trivia(question: "Which territory did the United States purchase from Russia in 1867?", answer: "Alaska", category: .usHistory),
        Trivia(question: "Who was the President of the United States during the War of 1812?", answer: "James Madison", category: .usHistory),
        Trivia(question: "Which US President is known for his role in the Watergate scandal and subsequent resignation from office?", answer: "Richard Nixon", category: .usHistory),
        Trivia(question: "Who was the first Secretary of the Treasury of the United States?", answer: "Alexander Hamilton", category: .usHistory),
        Trivia(question: "Which US President issued the Emancipation Proclamation during the Civil War?", answer: "Abraham Lincoln", category: .usHistory),
        Trivia(question: "Who was the first woman to fly solo across the Atlantic Ocean?", answer: "Amelia Earhart", category: .usHistory),
        Trivia(question: "What event led to the United States' entry into World War II?", answer: "Attack on Pearl Harbor", category: .usHistory),
        Trivia(question: "Who was the main author of the United States Constitution?", answer: "James Madison", category: .usHistory),
        Trivia(question: "Which amendment to the US Constitution abolished slavery?", answer: "13th Amendment", category: .usHistory),
        Trivia(question: "Who invented the assembly line production system?", answer: "Henry Ford", category: .usHistory),
        Trivia(question: "What was the period of tension between the United States and the Soviet Union called?", answer: "Cold War", category: .usHistory),
        Trivia(question: "Who was the main author of the United States Constitution?", answer: "James Madison", category: .usHistory),
        Trivia(question: "Which amendment to the US Constitution abolished slavery?", answer: "13th Amendment", category: .usHistory),
        Trivia(question: "Who invented the assembly line production system?", answer: "Henry Ford", category: .usHistory),
        Trivia(question: "Which American general famously stated 'I shall return' upon leaving the Philippines during World War II?", answer: "Douglas MacArthur", category: .usHistory),
        Trivia(question: "Who was the first African American to serve as Secretary of State of the United States?", answer: "Colin Powell", category: .usHistory),
        Trivia(question: "What was the name of the ship that brought the Pilgrims to America in 1620?", answer: "Mayflower", category: .usHistory),
        Trivia(question: "Which amendment to the US Constitution guarantees freedom of speech, religion, and the press?", answer: "First Amendment", category: .usHistory),
        Trivia(question: "Who was the President of the United States during the Louisiana Purchase?", answer: "Thomas Jefferson", category: .usHistory),
        Trivia(question: "What was the name of the agreement that ended the American Revolution and recognized American independence?", answer: "Treaty of Paris", category: .usHistory),
        Trivia(question: "Which US President is known for his leadership during the Civil Rights Movement and signed the Civil Rights Act of 1964?", answer: "Lyndon B. Johnson", category: .usHistory),
        Trivia(question: "Who was the commander-in-chief of the Continental Army during the American Revolutionary War?", answer: "George Washington", category: .usHistory),
        Trivia(question: "What was the name of the movement to promote the production and sale of alcohol in the United States during the early 20th century?", answer: "Prohibition", category: .usHistory),
        Trivia(question: "Who was the President of the United States during the Mexican-American War?", answer: "James K. Polk", category: .usHistory),
        Trivia(question: "Which US President ordered the dropping of atomic bombs on Hiroshima and Nagasaki?", answer: "Harry S. Truman", category: .usHistory),
        Trivia(question: "Who was the first woman to be appointed to the United States Supreme Court?", answer: "Sandra Day O'Connor", category: .usHistory),
        Trivia(question: "What was the name of the economic program implemented by President Franklin D. Roosevelt to address the Great Depression?", answer: "New Deal", category: .usHistory),
        Trivia(question: "Who was the President of the Confederate States during the American Civil War?", answer: "Jefferson Davis", category: .usHistory),
        Trivia(question: "Which territory did the United States purchase from Russia in 1867?", answer: "Alaska", category: .usHistory),
        Trivia(question: "Who was the President of the United States during the War of 1812?", answer: "James Madison", category: .usHistory),
        Trivia(question: "Which US President is known for his role in the Watergate scandal and subsequent resignation from office?", answer: "Richard Nixon", category: .usHistory),
        Trivia(question: "Who was the first Secretary of the Treasury of the United States?", answer: "Alexander Hamilton", category: .usHistory),
        Trivia(question: "Which US President issued the Emancipation Proclamation during the Civil War?", answer: "Abraham Lincoln", category: .usHistory),
        Trivia(question: "Who was the first woman to fly solo across the Atlantic Ocean?", answer: "Amelia Earhart", category: .usHistory),
        Trivia(question: "What event led to the United States' entry into World War II?", answer: "Attack on Pearl Harbor", category: .usHistory),
        Trivia(question: "Who was the main author of the United States Constitution?", answer: "James Madison", category: .usHistory),
        Trivia(question: "Which amendment to the US Constitution abolished slavery?", answer: "13th Amendment", category: .usHistory),
        Trivia(question: "Who invented the assembly line production system?", answer: "Henry Ford", category: .usHistory),
        Trivia(question: "What was the period of tension between the United States and the Soviet Union called?", answer: "Cold War", category: .usHistory),
        Trivia(question: "Who was the main author of the United States Constitution?", answer: "James Madison", category: .usHistory),
        Trivia(question: "Which amendment to the US Constitution abolished slavery?", answer: "13th Amendment", category: .usHistory),
        Trivia(question: "Who invented the assembly line production system?", answer: "Henry Ford", category: .usHistory),
        Trivia(question: "What was the period of tension between the United States and the Soviet Union called?", answer: "Cold War", category: .usHistory),
        Trivia(question: "Who was the main author of the United States Constitution?", answer: "James Madison", category: .usHistory),
        Trivia(question: "Which amendment to the US Constitution abolished slavery?", answer: "13th Amendment", category: .usHistory),
        Trivia(question: "Who invented the assembly line production system?", answer: "Henry Ford", category: .usHistory),
        Trivia(question: "What was the period of tension between the United States and the Soviet Union called?", answer: "Cold War", category: .usHistory),
        Trivia(question: "Who was the main author of the United States Constitution?", answer: "James Madison", category: .usHistory),
        Trivia(question: "Which amendment to the US Constitution abolished slavery?", answer: "13th Amendment", category: .usHistory),
        Trivia(question: "Who invented the assembly line production system?", answer: "Henry Ford", category: .usHistory),
        Trivia(question: "What was the period of tension between the United States and the Soviet Union called?", answer: "Cold War", category: .usHistory),
        Trivia(question: "Who was the main author of the United States Constitution?", answer: "James Madison", category: .usHistory),
        Trivia(question: "Which amendment to the US Constitution abolished slavery?", answer: "13th Amendment", category: .usHistory),
        Trivia(question: "Who invented the assembly line production system?", answer: "Henry Ford", category: .usHistory),
        Trivia(question: "What was the period of tension between the United States and the Soviet Union called?", answer: "Cold War", category: .usHistory),
        Trivia(question: "Who was the main author of the United States Constitution?", answer: "James Madison", category: .usHistory),
        Trivia(question: "Which amendment to the US Constitution abolished slavery?", answer: "13th Amendment", category: .usHistory),
        Trivia(question: "Who invented the assembly line production system?", answer: "Henry Ford", category: .usHistory),
        Trivia(question: "What was the period of tension between the United States and the Soviet Union called?", answer: "Cold War", category: .usHistory),
        Trivia(question: "Who was the main author of the United States Constitution?", answer: "James Madison", category: .usHistory),
        Trivia(question: "Which amendment to the US Constitution abolished slavery?", answer: "13th Amendment", category: .usHistory),
        Trivia(question: "Who was the main author of the United States Constitution?", answer: "James Madison", category: .usHistory),
        Trivia(question: "Which amendment to the US Constitution abolished slavery?", answer: "13th Amendment", category: .usHistory),
        Trivia(question: "Who invented the assembly line production system?", answer: "Henry Ford", category: .usHistory),
        Trivia(question: "What was the period of tension between the United States and the Soviet Union called?", answer: "Cold War", category: .usHistory),
        Trivia(question: "Who was the main author of the United States Constitution?", answer: "James Madison", category: .usHistory),
        Trivia(question: "Which amendment to the US Constitution abolished slavery?", answer: "13th Amendment", category: .usHistory),
        Trivia(question: "Who invented the assembly line production system?", answer: "Henry Ford", category: .usHistory),
        Trivia(question: "What was the period of tension between the United States and the Soviet Union called?", answer: "Cold War", category: .usHistory),
        Trivia(question: "Who was the main author of the United States Constitution?", answer: "James Madison", category: .usHistory),
        Trivia(question: "Which amendment to the US Constitution abolished slavery?", answer: "13th Amendment", category: .usHistory),
        Trivia(question: "Who invented the assembly line production system?", answer: "Henry Ford", category: .usHistory),
        Trivia(question: "What was the period of tension between the United States and the Soviet Union called?", answer: "Cold War", category: .usHistory),
        Trivia(question: "Who was the main author of the United States Constitution?", answer: "James Madison", category: .usHistory),
        Trivia(question: "Which amendment to the US Constitution abolished slavery?", answer: "13th Amendment", category: .usHistory),
        Trivia(question: "Who invented the assembly line production system?", answer: "Henry Ford", category: .usHistory),
        Trivia(question: "What was the period of tension between the United States and the Soviet Union called?", answer: "Cold War", category: .usHistory),
        Trivia(question: "Who was the main author of the United States Constitution?", answer: "James Madison", category: .usHistory),
        Trivia(question: "Which amendment to the US Constitution abolished slavery?", answer: "13th Amendment", category: .usHistory),
        Trivia(question: "Who invented the assembly line production system?", answer: "Henry Ford", category: .usHistory),
        Trivia(question: "What was the period of tension between the United States and the Soviet Union called?", answer: "Cold War", category: .usHistory),
        Trivia(question: "Who was the main author of the United States Constitution?", answer: "James Madison", category: .usHistory),
        Trivia(question: "Which amendment to the US Constitution abolished slavery?", answer: "13th Amendment", category: .usHistory),
        Trivia(question: "Who invented the assembly line production system?", answer: "Henry Ford", category: .usHistory),
        Trivia(question: "What was the period of tension between the United States and the Soviet Union called?", answer: "Cold War", category: .usHistory),
        Trivia(question: "Who was the main author of the United States Constitution?", answer: "James Madison", category: .usHistory),
        Trivia(question: "Which amendment to the US Constitution abolished slavery?", answer: "13th Amendment", category: .usHistory),
        Trivia(question: "Who invented the assembly line production system?", answer: "Henry Ford", category: .usHistory),
        Trivia(question: "What was the period of tension between the United States and the Soviet Union called?", answer: "Cold War", category: .usHistory),
        Trivia(question: "Who was the main author of the United States Constitution?", answer: "James Madison", category: .usHistory),
        Trivia(question: "Which amendment to the US Constitution abolished slavery?", answer: "13th Amendment", category: .usHistory),
        Trivia(question: "Who invented the assembly line production system?", answer: "Henry Ford", category: .usHistory),
        Trivia(question: "What was the period of tension between the United States and the Soviet Union called?", answer: "Cold War", category: .usHistory),
        Trivia(question: "Who was the main author of the United States Constitution?", answer: "James Madison", category: .usHistory),
        Trivia(question: "Which amendment to the US Constitution abolished slavery?", answer: "13th Amendment", category: .usHistory),
        Trivia(question: "Who invented the assembly line production system?", answer: "Henry Ford", category: .usHistory),
        Trivia(question: "What was the period of tension between the United States and the Soviet Union called?", answer: "Cold War", category: .usHistory),
        Trivia(question: "Who was the main author of the United States Constitution?", answer: "James Madison", category: .usHistory),
        Trivia(question: "Which amendment to the US Constitution abolished slavery?", answer: "13th Amendment", category: .usHistory),
        Trivia(question: "Who invented the assembly line production system?", answer: "Henry Ford", category: .usHistory),
        Trivia(question: "What was the period of tension between the United States and the Soviet Union called?", answer: "Cold War", category: .usHistory),
        Trivia(question: "Who was the main author of the United States Constitution?", answer: "James Madison", category: .usHistory),
        Trivia(question: "Which amendment to the US Constitution abolished slavery?", answer: "13th Amendment", category: .usHistory),
        Trivia(question: "Who invented the assembly line production system?", answer: "Henry Ford", category: .usHistory),
        Trivia(question: "What was the period of tension between the United States and the Soviet Union called?", answer: "Cold War", category: .usHistory),
    ]
}
